relativeURLs = true
title = "Ke Feng"
theme = "academimal"
sectionPagesMenu = "main"
defaultContentLanguage = "en"
ignorefiles = [ "hugo_travis_ci", ".travis.yml" ]

[params]
    shortbio = "PhD in Accounting, University of Alberta"
    logo = "UofA_SOB_Headshots_010419_LR-143.jpg" 
    
